language: cpp
sudo: required

cache:
  directories:
    - $HOME/Library/Caches/Homebrew

matrix:
  include:
    - os: osx
      osx_image: xcode8
      compiler: clang  
    - os: osx
      osx_image: xcode8.3
      compiler: clang
    - os: osx
      osx_image: xcode9.3
      compiler: clang

install:
  - rm /usr/local/include/c++ # https://github.com/Homebrew/brew/issues/1742#issuecomment-277308817
  - brew update
  - brew install dreal/dreal/dreal --only-dependencies || true
  - brew install dreal/dreal/dreal --build-from-source -v

script:
  - wget https://raw.githubusercontent.com/dreal/dreal4/master/dreal/test/smt2/01.smt2
  - /usr/local/opt/dreal/bin/dreal 01.smt2
  - export PKG_CONFIG_PATH=/usr/local/opt/ibex@2.6.5/share/pkgconfig:${PKG_CONFIG_PATH}
  - curl -o check_sat.cc  https://raw.githubusercontent.com/dreal/dreal-bazel-example-project/master/check_sat.cc
  - clang++ --std=c++14 check_sat.cc `pkg-config dreal --cflags --libs` && ./a.out
  - wget https://raw.githubusercontent.com/dreal/dreal4/master/dreal/api/test/api_test.py
  - python2 api_test.py --verbose
  - brew test dreal

notifications:
  email:
    recipients:
     - soonho.kong@gmail.com
