language: cpp
sudo: required

cache:
  directories:
    - $HOME/Library/Caches/Homebrew
rvm: system
matrix:
  include:
    - os: osx
      osx_image: xcode9.4  # macOS-10.13
      compiler: clang
    - os: osx
      osx_image: xcode10.2 # macOS-10.14
      compiler: clang

install:
  - brew tap dreal/dreal
  - brew update
  - brew install dreal/dreal/dreal --only-dependencies || true
  - brew install dreal/dreal/dreal --build-from-source -v
  - brew install python3

script:
  - wget https://raw.githubusercontent.com/dreal/dreal4/master/dreal/test/smt2/01.smt2
  - /usr/local/opt/dreal/bin/dreal 01.smt2
  - export PKG_CONFIG_PATH=/usr/local/opt/ibex@2.7.4/share/pkgconfig:${PKG_CONFIG_PATH}
  - curl -o check_sat.cc  https://raw.githubusercontent.com/dreal/dreal-bazel-example-project/master/check_sat.cc
  - clang++ --std=c++14 check_sat.cc `pkg-config dreal --cflags --libs` && ./a.out
  - wget https://raw.githubusercontent.com/dreal/dreal4/master/dreal/test/python/api_test.py
  - wget https://raw.githubusercontent.com/dreal/dreal4/master/dreal/test/python/solver_test.py
  - python3 -m pip install dreal
  - python3 api_test.py --verbose
  - python3 solver_test.py --verbose
  - brew test dreal
  - brew linkage --test dreal

notifications:
  email:
    recipients:
     - soonho.kong@gmail.com
