name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 8 * * *'

jobs:
  macos_catalina:
    name: macos catalina
    runs-on: macos-10.15
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: run_script
      	run: ./ci/script.sh
        shell: zsh -efuo pipefail {0}
